CREATE TABLE TBL_ATTACH(
	ATTACH_SEQ INT,
	ATTACH_NAME VARCHAR2(100),
	BOARD_SEQ INT,
	CONSTRAINT TBL_ATTACH_PK PRIMARY KEY(ATTACH_SEQ),
	CONSTRAINT TBL_ATTACH_BOARD_SEQ_FK FOREIGN KEY (BOARD_SEQ) REFERENCES TBL_BOARD(BOARD_SEQ)
);

CREATE SEQUENCE TBL_ATTACH_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10000;

