/*FK 위해서 보드 카테고리 테이블부터 먼저 생성*/
CREATE TABLE TBL_BOARD_CATEGORY
(
    BOARD_CATEGORY_ID      INT             NOT NULL, 
    BOARD_CATEGORY_NAME    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT TBL_BOARD_CATEGORY_PK PRIMARY KEY (BOARD_CATEGORY_ID)
);

INSERT INTO TBL_BOARD_CATEGORY 
VALUES(1, '자유');

INSERT INTO TBL_BOARD_CATEGORY 
VALUES(2, '정보');

INSERT INTO TBL_BOARD_CATEGORY 
VALUES(3, '홍보');

INSERT INTO TBL_BOARD_CATEGORY 
VALUES(4, '토론');

SELECT * FROM TBL_BOARD_CATEGORY;

CREATE TABLE TBL_BOARD
(
    BOARD_SEQ            INT               NOT NULL, 
    BOARD_TITLE          VARCHAR2(50)      NOT NULL, 
    BOARD_TEXT           VARCHAR2(4000)    NOT NULL, 
    BOARD_DATE           DATE              NOT NULL, 
    BOARD_HITS           INT               DEFAULT 0, 
    BOARD_LIKE           INT               DEFAULT 0, 
    MEMBER_SEQ           INT               NOT NULL, 
    BOARD_CATEGORY_ID    INT               NOT NULL, 
    CONSTRAINT TBL_BOARD_PK PRIMARY KEY (BOARD_SEQ),
    CONSTRAINT TBL_BOARD_MEMBER_SEQ_FK FOREIGN KEY (MEMBER_SEQ) REFERENCES TBL_MEMBER(MEMBER_SEQ),
    CONSTRAINT TBL_BOARD_BOARD_CATEGORY_ID_FK FOREIGN KEY (BOARD_CATEGORY_ID) REFERENCES TBL_BOARD_CATEGORY(BOARD_CATEGORY_ID)
);

CREATE SEQUENCE TBL_BOARD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000;


INSERT INTO TBL_BOARD
(BOARD_SEQ, BOARD_TITLE, BOARD_TEXT, BOARD_DATE, BOARD_HITS, BOARD_LIKE, MEMBER_SEQ, BOARD_CATEGORY_ID)
VALUES(TBL_BOARD_SEQ.NEXTVAL, '초상권?', '길거리 사진에 초상권이 있나요?', SYSDATE, 0, 0, 13, 4); 

DELETE FROM TBL_BOARD WHERE MEMBER_SEQ = 13;

SELECT * FROM TBL_BOARD;
