CREATE TABLE TBL_CATEGORY
(
    PARENT_ID        INT             NULL, 
    CATEGORY_ID      INT             NOT NULL, 
    CATEGORY_TYPE    VARCHAR2(40)    NOT NULL, 
    CONSTRAINT TBL_CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE TBL_CATEGORY
    ADD CONSTRAINT FK_TBL_CATEGORY_PARENT_ID_TBL_ FOREIGN KEY (PARENT_ID)
        REFERENCES TBL_CATEGORY (CATEGORY_ID);
        
SELECT * FROM TBL_CATEGORY;

INSERT INTO TBL_CATEGORY
VALUES(NULL, 1, '사진');

INSERT INTO TBL_CATEGORY
VALUES(NULL, 2, '미디어 아트');

INSERT INTO TBL_CATEGORY
VALUES(NULL, 3, '영상');

INSERT INTO TBL_CATEGORY
VALUES(NULL, 4, '디자인');

INSERT INTO TBL_CATEGORY
VALUES(1, 11, '추상');

INSERT INTO TBL_CATEGORY
VALUES(1, 12, '패션');

INSERT INTO TBL_CATEGORY
VALUES(1, 13, '건축');

INSERT INTO TBL_CATEGORY
VALUES(1, 14, '모던');

INSERT INTO TBL_CATEGORY
VALUES(1, 15, '인물');

INSERT INTO TBL_CATEGORY
VALUES(1, 16, '동물');

INSERT INTO TBL_CATEGORY
VALUES(1, 17, '자연');

INSERT INTO TBL_CATEGORY
VALUES(1, 18, '기타');

INSERT INTO TBL_CATEGORY
VALUES(2, 21, '인터렉티브 아트');

INSERT INTO TBL_CATEGORY
VALUES(2, 22, '프로젝션 맵핑');

INSERT INTO TBL_CATEGORY
VALUES(2, 23, '미디어 파사드');

INSERT INTO TBL_CATEGORY
VALUES(2, 24, '디지털 아트');

INSERT INTO TBL_CATEGORY
VALUES(2, 25, '라이트 아트');

INSERT INTO TBL_CATEGORY
VALUES(2, 26, '키네틱 아트');

INSERT INTO TBL_CATEGORY
VALUES(2, 27, '미디어 퍼포먼스');

INSERT INTO TBL_CATEGORY
VALUES(2, 28, '기타');

INSERT INTO TBL_CATEGORY
VALUES(3, 31, '영화');

INSERT INTO TBL_CATEGORY
VALUES(3, 32, '애니메이션');

INSERT INTO TBL_CATEGORY
VALUES(3, 33, '기타');

INSERT INTO TBL_CATEGORY
VALUES(4, 41, '그림');

INSERT INTO TBL_CATEGORY
VALUES(4, 42, '일러스트');

INSERT INTO TBL_CATEGORY
VALUES(4, 43, '도예');

INSERT INTO TBL_CATEGORY
VALUES(4, 44, '가구');

INSERT INTO TBL_CATEGORY
VALUES(4, 45, '조명');

INSERT INTO TBL_CATEGORY
VALUES(4, 46, '기타');


