DROP TABLE TBL_EXHIBITION;

CREATE TABLE TBL_EXHIBITION
(
    EXHIBITION_SEQ       INT               NOT NULL, 
    MEMBER_SEQ           INT               NOT NULL, 
    EXHIBITION_NAME      VARCHAR2(50)      NULL, 
    EXHIBITION_TEXT      VARCHAR2(3000)    NULL, 
    START_DATE           VARCHAR2(40)      NULL, 
    END_DATE             VARCHAR2(40)      NULL, 
    CATEGORY_ID          INT               NULL, 
    REPORT_CNT           INT               NULL, 
    EXHIBITION_STATUS    INT               NULL, 
    CONSTRAINT TBL_EXHIBITION_PK PRIMARY KEY (EXHIBITION_SEQ)
);

ALTER TABLE TBL_EXHIBITION
    ADD CONSTRAINT FK_TBL_EXHIBITION_MEMBER_SEQ FOREIGN KEY (MEMBER_SEQ)
        REFERENCES TBL_MEMBER (MEMBER_SEQ);

ALTER TABLE TBL_EXHIBITION
    ADD CONSTRAINT FK_TBL_EXHIBITION_CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
        REFERENCES TBL_CATEGORY (CATEGORY_ID);
        
CREATE SEQUENCE TBL_EXHIBITION_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM TBL_EXHIBITION;

TRUNCATE TABLE TBL_EXHIBITION;

/*12.28추가*/
ALTER TABLE TBL_EXHIBITION
	ADD PARENT_CATEGORY_ID INT NULL;


DROP TRIGGER TBL_EXHIBITION_AI_TRG;
/*12.30추가*/
ALTER TABLE TBL_EXHIBITION ADD LIKE_CNT INT DEFAULT 0 NULL;

/**테스트*/
SELECT * FROM TBL_EXHIBITION WHERE PARENT_CATEGORY_ID =1 ORDER BY EXHIBITION_SEQ DESC

SELECT *
FROM
(SELECT ROWNUM R, D.* FROM
(SELECT * FROM TBL_EXHIBITION WHERE PARENT_CATEGORY_ID =1 ORDER BY EXHIBITION_SEQ DESC) D) B
WHERE (B.R BETWEEN
1 AND 12)

/*1월 4일 추가*/
ALTER TABLE TBL_EXHIBITION ADD MAIN_PHOTO_DATA VARCHAR2(2000);

