CREATE TABLE TBL_MEMBER
(
    MEMBER_SEQ         INT               NOT NULL, 
    MEMBER_NAME        VARCHAR2(20)      NOT NULL, 
    MEMBER_ID          VARCHAR2(20)      NOT NULL, 
    MEMBER_PW          VARCHAR2(20)      NOT NULL, 
    MEMBER_NICKNAME    VARCHAR2(20)      NULL, 
    MEMBER_TEXT        VARCHAR2(3000)    NULL, 
    MEMBER_EMAIL       VARCHAR2(20)      NULL, 
    CONSTRAINT TBL_MEMBER_PK PRIMARY KEY (MEMBER_SEQ)
);

SELECT * FROM TBL_MEMBER;

CREATE SEQUENCE TBL_MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000;

INSERT INTO TBL_MEMBER
(MEMBER_SEQ, MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_TEXT, MEMBER_EMAIL)
VALUES(TBL_MEMBER_SEQ.NEXTVAL, '김밥', 'test1', '1234', '천국', '음식 사진을 찍는 것을 좋아합니다', 'kimbab@heaven.com');

INSERT INTO TBL_MEMBER
(MEMBER_SEQ, MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_TEXT, MEMBER_EMAIL)
VALUES(TBL_MEMBER_SEQ.NEXTVAL, '돈까스', 'test2', '1234', '스윙스', '래퍼 사진 찍는 것을 즐기는 전문 사진사입니다', 'donga@swings.com');

INSERT INTO TBL_MEMBER
(MEMBER_SEQ, MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_TEXT, MEMBER_EMAIL)
VALUES(TBL_MEMBER_SEQ.NEXTVAL, '한국인', 'test3', '1234', 'korea', '사진을 배우고 싶습니다', 'korea@korea.co.kr');

INSERT INTO TBL_MEMBER
(MEMBER_SEQ, MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_TEXT, MEMBER_EMAIL)
VALUES(TBL_MEMBER_SEQ.NEXTVAL, '널테스트', 'test4', '1234', NULL, NULL, 'null@null.co.kr');

ALTER TABLE TBL_MEMBER MODIFY MEMBER_EMAIL VARCHAR2(20) NOT NULL;

ALTER TABLE TBL_MEMBER MODIFY MEMBER_PW VARCHAR2(50);

/*12월 19일 추가*/
ALTER TABLE TBL_MEMBER MODIFY MEMBER_EMAIL VARCHAR2(50);

ALTER TABLE TBL_MEMBER ADD MEMBER_PROFILE_PIC VARCHAR2(100)

SELECT * FROM TBL_MEMBER;

/*12월 27일 추가*/
ALTER TABLE TBL_MEMBER ADD MEMBER_EMAIL_HASH VARCHAR2(1000)

ALTER TABLE TBL_MEMBER ADD MEMBER_EMAIL_CHECKED int;

SELECT * FROM TBL_MEMBER;

DELETE FROM TBL_MEMBER tm WHERE member_seq = 25

