CREATE TABLE TBL_PHOTO
(
    PHOTO_SEQ         INT               NOT NULL, 
    PHOTO_DATA			VARCHAR2(200)	NOT NULL,
    PHOTO_NAME			VARCHAR2(50)	NULL,
    PHOTO_TEXT        VARCHAR2(3000)    NULL, 
   	MEMBER_SEQ		INT					NOT NULL,
    CONSTRAINT TBL_PHOTO_PK PRIMARY KEY (PHOTO_SEQ),
    CONSTRAINT TBL_PHOTO_MEMBER_SEQ_FK FOREIGN KEY(MEMBER_SEQ)
    REFERENCES TBL_MEMBER(MEMBER_SEQ)
);

SELECT * FROM TBL_PHOTO;


DROP TABLE TBL_PHOTO; /*주의*/
/*
DROP TABLE TBL_MEMBER;
DROP TABLE TBL_BOARD;
DROP TABLE TBL_BOARD_CATEGORY; 
DROP TABLE TBL_CATEGORY; 
DROP TABLE TBL_COMMENT;
DROP TABLE TBL_EXHIBITION;
DROP TABLE TBL_MEMBER; 
DROP TABLE TBL_MUSIC; 
*/


CREATE SEQUENCE TBL_PHOTO_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000;