CREATE TABLE TBL_PHOTO_EXHIBITION(
	PHOTO_SEQ INT,
	EXHIBITION_SEQ INT,
	CONSTRAINT TBL_PHOTO_EX_PHOTO_SEQ_FK FOREIGN KEY(PHOTO_SEQ) REFERENCES TBL_PHOTO(PHOTO_SEQ),
	CONSTRAINT TBL_PHOTO_EX_EX_SEQ_FK FOREIGN KEY(EXHIBITION_SEQ) REFERENCES TBL_EXHIBITION(EXHIBITION_SEQ)
);

SELECT * FROM TBL_PHOTO_EXHIBITION;

TRUNCATE TABLE TBL_PHOTO_EXHIBITION;

