CREATE TABLE TBL_REPORT
(
    EXHIBITION_SEQ    INT               NOT NULL, 
    REPORT_SEQ        INT               NULL, 
    REPORT_TITLE      VARCHAR2(40)      NULL, 
    REPORT_TEXT       VARCHAR2(3000)    NULL, 
    CONSTRAINT TBL_REPORT_PK PRIMARY KEY (REPORT_SEQ)
)

CREATE SEQUENCE TBL_REPORT_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE TBL_REPORT
    ADD CONSTRAINT FK_TBL_REPORT_EXHIBITION_SEQ_T FOREIGN KEY (EXHIBITION_SEQ)
        REFERENCES TBL_EXHIBITION (EXHIBITION_SEQ)
        
SELECT * FROM TBL_REPORT;