DROP TABLE TBL_SUBSCRIBE;

CREATE TABLE TBL_SUBSCRIBE
(
    FOLLOWING_ID    INT    NULL, 
    FOLLOWED_ID     INT    NULL   
);

CREATE SEQUENCE TBL_SUBSCRIBE_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE TBL_SUBSCRIBE
    ADD CONSTRAINT FK_TBL_SUBSCRIBE_FOLLOWING_ID_ FOREIGN KEY (FOLLOWING_ID)
        REFERENCES TBL_MEMBER (MEMBER_SEQ);

SELECT * FROM TBL_SUBSCRIBE;

/*로그인한 유저가 다른 사람의 유저페이지에 들어가서 구독을 누른다고 가정*/
/*FOLLOWED(팔로워)에는 SESSION_ID, FOLLOWING에는 유저페이지 주인의 MEMBER_ID*/

/*더미 데이터*/
INSERT INTO TBL_SUBSCRIBE
(FOLLOWING_ID, FOLLOWED_ID)
VALUES(1, 2);

INSERT INTO TBL_SUBSCRIBE
(FOLLOWING_ID, FOLLOWED_ID)
VALUES(1, 3);

INSERT INTO TBL_SUBSCRIBE
(FOLLOWING_ID, FOLLOWED_ID)
VALUES(2, 1);

INSERT INTO TBL_SUBSCRIBE
(FOLLOWING_ID, FOLLOWED_ID)
VALUES(3, 1);

INSERT INTO TBL_SUBSCRIBE
(FOLLOWING_ID, FOLLOWED_ID)
VALUES(4, 1);

DELETE FROM TBL_SUBSCRIBE
WHERE FOLLOWING_ID=4 AND FOLLOWED_ID=1;

DELETE FROM TBL_SUBSCRIBE
WHERE FOLLOWING_ID=1 AND FOLLOWED_ID=25;

